import { PermissionKey, Student, User, UserRole, LegacyUserRole, ServerSession } from '../types';

export const ROLE_DISPLAY_NAMES: Record<LegacyUserRole, string> = {
  SystemAdmin: 'مدير النظام المركزي',
  SchoolAdmin: 'مدير إدارة المدرسة',
  Admin: 'مدير النظام',
  SchoolDirector: 'مدير المدرسة',
  StudentAffairs: 'شؤون الطلاب',
  TeacherAffairs: 'شؤون المعلمين والعاملين',
  QualityOfficer: 'مسؤول الجودة',
  TrainingOfficer: 'مسؤول التدريب والتوجيه المهني',
  SocialSpecialist: 'الأخصائي الاجتماعي',
  Teacher: 'معلم',
  AdministrativeEmployee: 'موظف إداري',
  HR: 'شؤون المعلمين والعاملين',
  Supervisor: 'مشرف تربوي / إداري',
  BehaviorOfficer: 'مسؤول السلوك والانضباط',
  Employee: 'موظف',
  Viewer: 'مستعرض (قراءة فقط)',
  Parent: 'ولي أمر (جهة اتصال - غير مصرح بالدخول)',
  Student: 'طالب (سجل مدرسي - لا يوجد حساب)',
};

export const PERMISSION_ALIASES: Record<string, PermissionKey[]> = {
  'schools.manage': [],
  'schools.view': [],
  'attendance.students.view': ['studentAttendance.view'],
  'studentAttendance.view': ['attendance.students.view'],
  'attendance.students.manage': ['studentAttendance.manage'],
  'studentAttendance.manage': ['attendance.students.manage'],
  'attendance.staff.view': ['teacherAttendance.view'],
  'teacherAttendance.view': ['attendance.staff.view'],
  'attendance.staff.manage': ['teacherAttendance.manage'],
  'teacherAttendance.manage': ['attendance.staff.manage'],
  'employees.view': ['teachers.view'],
  'teachers.view': ['employees.view'],
  'employees.create': ['teachers.create'],
  'teachers.create': ['employees.create'],
  'employees.edit': ['teachers.edit'],
  'teachers.edit': ['employees.edit'],
  'employees.delete': ['teachers.delete'],
  'teachers.delete': ['employees.delete'],
  'employees.import': ['teachers.import'],
  'teachers.import': ['employees.import'],
  'timetable.view': ['schedule.view'],
  'schedule.view': ['timetable.view'],
  'timetable.manage': ['schedule.manage'],
  'schedule.manage': ['timetable.manage'],
  'timetable.publish': ['schedule.publish'],
  'schedule.publish': ['timetable.publish'],
  'curriculum.view': ['lessonContent.view'],
  'lessonContent.view': ['curriculum.view'],
  'leaves.own.view': ['leaves.view'],
  'leaves.view': ['leaves.own.view'],
  'leaves.own.create': ['leaves.create'],
  'leaves.create': ['leaves.own.create'],
  'settings.view': ['settings.manage'],
};

const ADMIN_ROLE_PERMISSIONS: Partial<Record<PermissionKey, boolean>> = {
    'schools.view': true,
    'schools.manage': true,
    'users.view': true,
    'users.create': true,
    'users.edit': true,
    'users.disable': true,
    'users.resetPassword': true,
    'users.manageRoles': true,
    'users.manage': true,
    'students.view': true,
    'students.create': true,
    'students.edit': true,
    'students.delete': true,
    'students.import': true,
    'employees.view': true,
    'employees.create': true,
    'employees.edit': true,
    'employees.delete': true,
    'employees.import': true,
    'teachers.view': true,
    'teachers.create': true,
    'teachers.edit': true,
    'teachers.delete': true,
    'teachers.import': true,
    'teacherPortal.access': true,
    'teacherSchedule.viewOwn': true,
    'teacherAccounts.manage': true,
    'attendance.students.view': true,
    'attendance.students.manage': true,
    'studentAttendance.view': true,
    'studentAttendance.create': true,
    'studentAttendance.edit': true,
    'studentAttendance.delete': true,
    'studentAttendance.manage': true,
    'attendance.staff.view': true,
    'attendance.staff.manage': true,
    'teacherAttendance.view': true,
    'teacherAttendance.create': true,
    'teacherAttendance.edit': true,
    'teacherAttendance.delete': true,
    'teacherAttendance.manage': true,
    'schoolAttendance.view': true,
    'schoolAttendance.create': true,
    'schoolAttendance.edit': true,
    'schoolAttendance.approve': true,
    'schoolAttendance.lock': true,
    'schoolAttendance.overrideLocked': true,
    'classAttendance.view': true,
    'classAttendance.create': true,
    'classAttendance.edit': true,
    'classAttendance.manageOwnLessons': true,
    'leaves.own.view': true,
    'leaves.own.create': true,
    'leaves.manage.view': true,
    'leaves.manage.approve': true,
    'leaves.manage.reject': true,
    'leaves.view': true,
    'leaves.create': true,
    'leaves.edit': true,
    'leaves.delete': true,
    'timetable.view': true,
    'timetable.manage': true,
    'timetable.import': true,
    'timetable.publish': true,
    'schedule.view': true,
    'schedule.manage': true,
    'schedule.publish': true,
    'schedule.cancelLesson': true,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': true,
    'schedule.viewConflicts': true,
    'curriculum.view': true,
    'curriculum.manage': true,
    'curriculum.assign': true,
    'lessonContent.view': true,
    'lessonContent.create': true,
    'lessonContent.edit': true,
    'lessonContent.editOwn': true,
    'lessonContent.publish': true,
    'lessonResources.manage': true,
    'homework.create': true,
    'homework.editOwn': true,
    'homework.publish': true,
    'academicYears.view': true,
    'academicYears.create': true,
    'academicYears.edit': true,
    'academicYears.close': true,
    'academicYears.reopen': true,
    'studentPromotion.view': true,
    'studentPromotion.execute': true,
    'studentPromotion.rollback': true,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': true,
    'student360.viewParentCommunication': true,
    'student360.editNotes': true,
    'behavior.view': true,
    'behavior.create': true,
    'behavior.edit': true,
    'behavior.delete': true,
    'behaviorCases.view': true,
    'behaviorCases.create': true,
    'behaviorCases.edit': true,
    'behaviorCases.close': true,
    'behaviorTypes.manage': true,
    'behaviorPoints.manage': true,
    'positiveBehavior.create': true,
    'parentCommunication.view': true,
    'parentCommunication.create': true,
    'settings.view': true,
    'settings.manage': true,
    'audit.view': true,
    'reports.view': true,
    'quality.view': true,
    'quality.create': true,
    'quality.evaluate': true,
    'quality.manageStandards': true,
    'quality.approve': true,
    'quality.viewDashboard': true,
};

const SYSTEM_ADMIN_PERMISSIONS: Partial<Record<PermissionKey, boolean>> = {
  ...ADMIN_ROLE_PERMISSIONS,
  'schools.view': true,
  'schools.manage': true, // SystemAdmin can manage schools
};

const SCHOOL_ADMIN_PERMISSIONS: Partial<Record<PermissionKey, boolean>> = {
  ...ADMIN_ROLE_PERMISSIONS,
  'schools.view': true,
  'schools.manage': false, // Crucial: SchoolAdmin CANNOT manage schools globally
};

export const DEFAULT_ROLE_PERMISSIONS: Record<LegacyUserRole, Partial<Record<PermissionKey, boolean>>> = {
  SystemAdmin: SYSTEM_ADMIN_PERMISSIONS,
  SchoolAdmin: SCHOOL_ADMIN_PERMISSIONS,
  Admin: ADMIN_ROLE_PERMISSIONS,
  StudentAffairs: {
    'students.view': true,
    'students.create': true,
    'students.edit': true,
    'students.delete': true,
    'students.import': true,
    'studentAttendance.view': true,
    'studentAttendance.create': true,
    'studentAttendance.edit': true,
    'studentAttendance.delete': true,
    'schoolAttendance.view': true,
    'schoolAttendance.create': true,
    'schoolAttendance.edit': true,
    'schoolAttendance.approve': true,
    'schoolAttendance.lock': true,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': true,
    'classAttendance.create': false,
    'classAttendance.edit': false,
    'classAttendance.manageOwnLessons': false,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': true,
    'studentPromotion.execute': true,
    'studentPromotion.rollback': false,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': true,
    'student360.viewParentCommunication': true,
    'student360.editNotes': true,
    'teachers.view': false,
    'teachers.create': false,
    'teachers.edit': false,
    'teachers.delete': false,
    'teachers.import': false,
    'teacherPortal.access': false,
    'teacherSchedule.viewOwn': false,
    'teacherAttendance.view': false,
    'teacherAttendance.create': false,
    'teacherAttendance.edit': false,
    'teacherAttendance.delete': false,
    'leaves.view': false,
    'leaves.create': false,
    'leaves.edit': false,
    'leaves.delete': false,
    'behavior.view': true,
    'behavior.create': true,
    'behavior.edit': true,
    'behavior.delete': false,
    'behaviorCases.view': true,
    'behaviorCases.create': true,
    'behaviorCases.edit': true,
    'behaviorCases.close': false,
    'behaviorTypes.manage': false,
    'behaviorPoints.manage': true,
    'positiveBehavior.create': true,
    'parentCommunication.view': true,
    'parentCommunication.create': true,
    'schedule.view': true,
    'schedule.manage': false,
    'schedule.publish': false,
    'schedule.cancelLesson': false,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': false,
    'schedule.viewConflicts': true,
    'lessonContent.view': true,
    'lessonContent.create': false,
    'lessonContent.edit': false,
    'lessonContent.editOwn': false,
    'lessonContent.publish': false,
    'lessonResources.manage': false,
    'homework.create': false,
    'homework.editOwn': false,
    'homework.publish': false,
    'settings.manage': false,
    'schools.view': false,
    'schools.manage': false,
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.disable': false,
    'users.resetPassword': false,
    'users.manageRoles': false,
    'users.manage': false,
    'attendance.students.view': true,
    'attendance.students.manage': true,
    'leaves.own.view': true,
    'leaves.own.create': true,
    'audit.view': false,
    'reports.view': true,
  },
  TeacherAffairs: {
    'students.view': false,
    'students.create': false,
    'students.edit': false,
    'students.delete': false,
    'students.import': false,
    'studentAttendance.view': false,
    'studentAttendance.create': false,
    'studentAttendance.edit': false,
    'studentAttendance.delete': false,
    'schoolAttendance.view': false,
    'schoolAttendance.create': false,
    'schoolAttendance.edit': false,
    'schoolAttendance.approve': false,
    'schoolAttendance.lock': false,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': false,
    'classAttendance.create': false,
    'classAttendance.edit': false,
    'classAttendance.manageOwnLessons': false,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': false,
    'studentPromotion.execute': false,
    'studentPromotion.rollback': false,
    'student360.view': false,
    'student360.viewAttendance': false,
    'student360.viewBehavior': false,
    'student360.viewParentCommunication': false,
    'student360.editNotes': false,
    'teachers.view': true,
    'teachers.create': true,
    'teachers.edit': true,
    'teachers.delete': true,
    'teachers.import': true,
    'teacherPortal.access': false,
    'teacherSchedule.viewOwn': false,
    'teacherAttendance.view': true,
    'teacherAttendance.create': true,
    'teacherAttendance.edit': true,
    'teacherAttendance.delete': true,
    'leaves.view': true,
    'leaves.create': true,
    'leaves.edit': true,
    'leaves.delete': true,
    'behavior.view': false,
    'behavior.create': false,
    'behavior.edit': false,
    'behavior.delete': false,
    'behaviorCases.view': false,
    'behaviorCases.create': false,
    'behaviorCases.edit': false,
    'behaviorCases.close': false,
    'behaviorTypes.manage': false,
    'behaviorPoints.manage': false,
    'positiveBehavior.create': false,
    'parentCommunication.view': false,
    'parentCommunication.create': false,
    'schedule.view': true,
    'schedule.manage': true,
    'schedule.publish': true,
    'schedule.cancelLesson': true,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': true,
    'schedule.viewConflicts': true,
    'lessonContent.view': false,
    'lessonContent.create': false,
    'lessonContent.edit': false,
    'lessonContent.editOwn': false,
    'lessonContent.publish': false,
    'lessonResources.manage': false,
    'homework.create': false,
    'homework.editOwn': false,
    'homework.publish': false,
    'settings.manage': false,
    'schools.view': false,
    'schools.manage': false,
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.disable': false,
    'users.resetPassword': false,
    'users.manageRoles': false,
    'users.manage': false,
    'employees.view': true,
    'employees.create': true,
    'employees.edit': true,
    'employees.import': true,
    'employees.delete': false,
    'attendance.staff.view': true,
    'attendance.staff.manage': true,
    'leaves.own.view': true,
    'leaves.own.create': true,
    'leaves.manage.view': true,
    'leaves.manage.approve': true,
    'leaves.manage.reject': true,
    'audit.view': false,
    'reports.view': true,
  },
  Teacher: {
    'students.view': true,
    'students.create': false,
    'students.edit': false,
    'students.delete': false,
    'students.import': false,
    'studentAttendance.view': true,
    'studentAttendance.create': true,
    'studentAttendance.edit': true,
    'studentAttendance.delete': false,
    'schoolAttendance.view': true,
    'schoolAttendance.create': false,
    'schoolAttendance.edit': false,
    'schoolAttendance.approve': false,
    'schoolAttendance.lock': false,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': true,
    'classAttendance.create': true,
    'classAttendance.edit': true,
    'classAttendance.manageOwnLessons': true,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': false,
    'studentPromotion.execute': false,
    'studentPromotion.rollback': false,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': true,
    'student360.viewParentCommunication': false,
    'student360.editNotes': false,
    'teachers.view': false,
    'teachers.create': false,
    'teachers.edit': false,
    'teachers.delete': false,
    'teachers.import': false,
    'teacherPortal.access': true,
    'teacherSchedule.viewOwn': true,
    'teacherAttendance.view': true,
    'teacherAttendance.create': false,
    'teacherAttendance.edit': false,
    'teacherAttendance.delete': false,
    'leaves.view': true,
    'leaves.create': true,
    'leaves.edit': false,
    'leaves.delete': false,
    'behavior.view': true,
    'behavior.create': true,
    'behavior.edit': false,
    'behavior.delete': false,
    'behaviorCases.view': true,
    'behaviorCases.create': false,
    'behaviorCases.edit': false,
    'behaviorCases.close': false,
    'behaviorTypes.manage': false,
    'behaviorPoints.manage': false,
    'positiveBehavior.create': true,
    'parentCommunication.view': false,
    'parentCommunication.create': false,
    'schedule.view': true,
    'schedule.manage': false,
    'schedule.publish': false,
    'schedule.cancelLesson': false,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': false,
    'schedule.viewConflicts': false,
    'lessonContent.view': true,
    'lessonContent.create': true,
    'lessonContent.edit': true,
    'lessonContent.editOwn': true,
    'lessonContent.publish': true,
    'lessonResources.manage': true,
    'homework.create': true,
    'homework.editOwn': true,
    'homework.publish': true,
    'settings.manage': false,
    'schools.view': false,
    'schools.manage': false,
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.disable': false,
    'users.resetPassword': false,
    'users.manageRoles': false,
    'users.manage': false,
    'timetable.view': true,
    'curriculum.view': true,
    'leaves.own.view': true,
    'leaves.own.create': true,
    'attendance.students.view': true,
    'audit.view': false,
    'reports.view': false,
  },
  SocialSpecialist: {
    'students.view': true,
    'students.create': false,
    'students.edit': false,
    'students.delete': false,
    'students.import': false,
    'studentAttendance.view': true,
    'studentAttendance.create': false,
    'studentAttendance.edit': false,
    'studentAttendance.delete': false,
    'schoolAttendance.view': true,
    'schoolAttendance.create': false,
    'schoolAttendance.edit': false,
    'schoolAttendance.approve': false,
    'schoolAttendance.lock': false,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': true,
    'classAttendance.create': false,
    'classAttendance.edit': false,
    'classAttendance.manageOwnLessons': false,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': false,
    'studentPromotion.execute': false,
    'studentPromotion.rollback': false,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': true,
    'student360.viewParentCommunication': true,
    'student360.editNotes': true,
    'teachers.view': false,
    'teachers.create': false,
    'teachers.edit': false,
    'teachers.delete': false,
    'teachers.import': false,
    'teacherPortal.access': false,
    'teacherSchedule.viewOwn': false,
    'teacherAttendance.view': false,
    'teacherAttendance.create': false,
    'teacherAttendance.edit': false,
    'teacherAttendance.delete': false,
    'leaves.view': false,
    'leaves.create': false,
    'leaves.edit': false,
    'leaves.delete': false,
    'behavior.view': true,
    'behavior.create': true,
    'behavior.edit': true,
    'behavior.delete': true,
    'behaviorCases.view': true,
    'behaviorCases.create': true,
    'behaviorCases.edit': true,
    'behaviorCases.close': true,
    'behaviorTypes.manage': true,
    'behaviorPoints.manage': true,
    'positiveBehavior.create': true,
    'parentCommunication.view': true,
    'parentCommunication.create': true,
    'schedule.view': true,
    'schedule.manage': false,
    'schedule.publish': false,
    'schedule.cancelLesson': false,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': false,
    'schedule.viewConflicts': false,
    'lessonContent.view': false,
    'lessonContent.create': false,
    'lessonContent.edit': false,
    'lessonContent.editOwn': false,
    'lessonContent.publish': false,
    'lessonResources.manage': false,
    'homework.create': false,
    'homework.editOwn': false,
    'homework.publish': false,
    'settings.manage': false,
    'schools.view': false,
    'schools.manage': false,
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.disable': false,
    'users.resetPassword': false,
    'users.manageRoles': false,
    'users.manage': false,
    'attendance.students.view': true,
    'leaves.own.view': true,
    'leaves.own.create': true,
    'audit.view': false,
    'reports.view': true,
  },
  Parent: {
    'students.view': true,
    'students.create': false,
    'students.edit': false,
    'students.delete': false,
    'students.import': false,
    'studentAttendance.view': true,
    'studentAttendance.create': false,
    'studentAttendance.edit': false,
    'studentAttendance.delete': false,
    'schoolAttendance.view': true,
    'schoolAttendance.create': false,
    'schoolAttendance.edit': false,
    'schoolAttendance.approve': false,
    'schoolAttendance.lock': false,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': true,
    'classAttendance.create': false,
    'classAttendance.edit': false,
    'classAttendance.manageOwnLessons': false,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': false,
    'studentPromotion.execute': false,
    'studentPromotion.rollback': false,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': true,
    'student360.viewParentCommunication': true,
    'student360.editNotes': false,
    'teachers.view': false,
    'teachers.create': false,
    'teachers.edit': false,
    'teachers.delete': false,
    'teachers.import': false,
    'teacherPortal.access': false,
    'teacherSchedule.viewOwn': false,
    'teacherAttendance.view': false,
    'teacherAttendance.create': false,
    'teacherAttendance.edit': false,
    'teacherAttendance.delete': false,
    'leaves.view': false,
    'leaves.create': false,
    'leaves.edit': false,
    'leaves.delete': false,
    'behavior.view': true,
    'behavior.create': false,
    'behavior.edit': false,
    'behavior.delete': false,
    'behaviorCases.view': false,
    'behaviorCases.create': false,
    'behaviorCases.edit': false,
    'behaviorCases.close': false,
    'behaviorTypes.manage': false,
    'behaviorPoints.manage': false,
    'positiveBehavior.create': false,
    'parentCommunication.view': false,
    'parentCommunication.create': false,
    'schedule.view': true,
    'schedule.manage': false,
    'schedule.publish': false,
    'schedule.cancelLesson': false,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': false,
    'schedule.viewConflicts': false,
    'lessonContent.view': true,
    'lessonContent.create': false,
    'lessonContent.edit': false,
    'lessonContent.editOwn': false,
    'lessonContent.publish': false,
    'lessonResources.manage': false,
    'homework.create': false,
    'homework.editOwn': false,
    'homework.publish': false,
    'settings.manage': false,
    'users.manage': false,
    'audit.view': false,
    'reports.view': false,
  },
  HR: {
    'students.view': true,
    'students.create': false,
    'students.edit': false,
    'students.delete': false,
    'students.import': false,
    'studentAttendance.view': true,
    'studentAttendance.create': false,
    'studentAttendance.edit': false,
    'studentAttendance.delete': false,
    'schoolAttendance.view': true,
    'schoolAttendance.create': false,
    'schoolAttendance.edit': false,
    'schoolAttendance.approve': false,
    'schoolAttendance.lock': false,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': false,
    'classAttendance.create': false,
    'classAttendance.edit': false,
    'classAttendance.manageOwnLessons': false,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': false,
    'studentPromotion.execute': false,
    'studentPromotion.rollback': false,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': false,
    'student360.viewParentCommunication': false,
    'student360.editNotes': false,
    'teachers.view': true,
    'teachers.create': true,
    'teachers.edit': true,
    'teachers.delete': false,
    'teachers.import': true,
    'teacherPortal.access': false,
    'teacherSchedule.viewOwn': false,
    'teacherAttendance.view': true,
    'teacherAttendance.create': true,
    'teacherAttendance.edit': true,
    'teacherAttendance.delete': false,
    'leaves.view': true,
    'leaves.create': true,
    'leaves.edit': true,
    'leaves.delete': false,
    'behavior.view': false,
    'behavior.create': false,
    'behavior.edit': false,
    'behavior.delete': false,
    'behaviorCases.view': false,
    'behaviorCases.create': false,
    'behaviorCases.edit': false,
    'behaviorCases.close': false,
    'behaviorTypes.manage': false,
    'behaviorPoints.manage': false,
    'positiveBehavior.create': false,
    'parentCommunication.view': false,
    'parentCommunication.create': false,
    'schedule.view': true,
    'schedule.manage': false,
    'schedule.publish': false,
    'schedule.cancelLesson': false,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': false,
    'schedule.viewConflicts': false,
    'lessonContent.view': false,
    'lessonContent.create': false,
    'lessonContent.edit': false,
    'lessonContent.editOwn': false,
    'lessonContent.publish': false,
    'lessonResources.manage': false,
    'homework.create': false,
    'homework.editOwn': false,
    'homework.publish': false,
    'settings.manage': false,
    'users.manage': false,
    'audit.view': false,
    'reports.view': true,
  },
  Supervisor: {
    'students.view': true,
    'students.create': true,
    'students.edit': true,
    'students.delete': false,
    'students.import': false,
    'studentAttendance.view': true,
    'studentAttendance.create': true,
    'studentAttendance.edit': true,
    'studentAttendance.delete': false,
    'schoolAttendance.view': true,
    'schoolAttendance.create': true,
    'schoolAttendance.edit': true,
    'schoolAttendance.approve': true,
    'schoolAttendance.lock': false,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': true,
    'classAttendance.create': true,
    'classAttendance.edit': true,
    'classAttendance.manageOwnLessons': true,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': true,
    'studentPromotion.execute': false,
    'studentPromotion.rollback': false,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': true,
    'student360.viewParentCommunication': true,
    'student360.editNotes': true,
    'teachers.view': true,
    'teachers.create': false,
    'teachers.edit': false,
    'teachers.delete': false,
    'teachers.import': false,
    'teacherPortal.access': true,
    'teacherSchedule.viewOwn': true,
    'teacherAttendance.view': true,
    'teacherAttendance.create': true,
    'teacherAttendance.edit': true,
    'teacherAttendance.delete': false,
    'leaves.view': true,
    'leaves.create': false,
    'leaves.edit': false,
    'leaves.delete': false,
    'behavior.view': true,
    'behavior.create': true,
    'behavior.edit': true,
    'behavior.delete': false,
    'behaviorCases.view': true,
    'behaviorCases.create': true,
    'behaviorCases.edit': true,
    'behaviorCases.close': false,
    'behaviorTypes.manage': false,
    'behaviorPoints.manage': true,
    'positiveBehavior.create': true,
    'parentCommunication.view': true,
    'parentCommunication.create': true,
    'schedule.view': true,
    'schedule.manage': true,
    'schedule.publish': true,
    'schedule.cancelLesson': true,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': true,
    'schedule.viewConflicts': true,
    'lessonContent.view': true,
    'lessonContent.create': true,
    'lessonContent.edit': true,
    'lessonContent.editOwn': true,
    'lessonContent.publish': true,
    'lessonResources.manage': true,
    'homework.create': true,
    'homework.editOwn': true,
    'homework.publish': true,
    'settings.manage': false,
    'users.manage': false,
    'audit.view': false,
    'reports.view': true,
  },
  BehaviorOfficer: {
    'students.view': true,
    'students.create': false,
    'students.edit': false,
    'students.delete': false,
    'students.import': false,
    'studentAttendance.view': true,
    'studentAttendance.create': false,
    'studentAttendance.edit': false,
    'studentAttendance.delete': false,
    'schoolAttendance.view': true,
    'schoolAttendance.create': false,
    'schoolAttendance.edit': false,
    'schoolAttendance.approve': false,
    'schoolAttendance.lock': false,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': true,
    'classAttendance.create': false,
    'classAttendance.edit': false,
    'classAttendance.manageOwnLessons': false,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': false,
    'studentPromotion.execute': false,
    'studentPromotion.rollback': false,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': true,
    'student360.viewParentCommunication': true,
    'student360.editNotes': true,
    'teachers.view': false,
    'teachers.create': false,
    'teachers.edit': false,
    'teachers.delete': false,
    'teachers.import': false,
    'teacherPortal.access': false,
    'teacherSchedule.viewOwn': false,
    'teacherAttendance.view': false,
    'teacherAttendance.create': false,
    'teacherAttendance.edit': false,
    'teacherAttendance.delete': false,
    'leaves.view': false,
    'leaves.create': false,
    'leaves.edit': false,
    'leaves.delete': false,
    'behavior.view': true,
    'behavior.create': true,
    'behavior.edit': true,
    'behavior.delete': true,
    'behaviorCases.view': true,
    'behaviorCases.create': true,
    'behaviorCases.edit': true,
    'behaviorCases.close': true,
    'behaviorTypes.manage': true,
    'behaviorPoints.manage': true,
    'positiveBehavior.create': true,
    'parentCommunication.view': true,
    'parentCommunication.create': true,
    'schedule.view': true,
    'schedule.manage': false,
    'schedule.publish': false,
    'schedule.cancelLesson': false,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': false,
    'schedule.viewConflicts': false,
    'lessonContent.view': false,
    'lessonContent.create': false,
    'lessonContent.edit': false,
    'lessonContent.editOwn': false,
    'lessonContent.publish': false,
    'lessonResources.manage': false,
    'homework.create': false,
    'homework.editOwn': false,
    'homework.publish': false,
    'settings.manage': false,
    'users.manage': false,
    'audit.view': false,
    'reports.view': true,
  },
  Employee: {
    'students.view': false,
    'students.create': false,
    'students.edit': false,
    'students.delete': false,
    'students.import': false,
    'studentAttendance.view': false,
    'studentAttendance.create': false,
    'studentAttendance.edit': false,
    'studentAttendance.delete': false,
    'schoolAttendance.view': false,
    'schoolAttendance.create': false,
    'schoolAttendance.edit': false,
    'schoolAttendance.approve': false,
    'schoolAttendance.lock': false,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': false,
    'classAttendance.create': false,
    'classAttendance.edit': false,
    'classAttendance.manageOwnLessons': false,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': false,
    'studentPromotion.execute': false,
    'studentPromotion.rollback': false,
    'student360.view': false,
    'student360.viewAttendance': false,
    'student360.viewBehavior': false,
    'student360.viewParentCommunication': false,
    'student360.editNotes': false,
    'teachers.view': false,
    'teachers.create': false,
    'teachers.edit': false,
    'teachers.delete': false,
    'teachers.import': false,
    'teacherPortal.access': false,
    'teacherSchedule.viewOwn': false,
    'teacherAttendance.view': true,
    'teacherAttendance.create': false,
    'teacherAttendance.edit': false,
    'teacherAttendance.delete': false,
    'leaves.view': true,
    'leaves.create': true,
    'leaves.edit': false,
    'leaves.delete': false,
    'behavior.view': false,
    'behavior.create': false,
    'behavior.edit': false,
    'behavior.delete': false,
    'behaviorCases.view': false,
    'behaviorCases.create': false,
    'behaviorCases.edit': false,
    'behaviorCases.close': false,
    'behaviorTypes.manage': false,
    'behaviorPoints.manage': false,
    'positiveBehavior.create': false,
    'parentCommunication.view': false,
    'parentCommunication.create': false,
    'schedule.view': false,
    'schedule.manage': false,
    'schedule.publish': false,
    'schedule.cancelLesson': false,
    'schedule.exportPdf': false,
    'schedule.manageSubstitution': false,
    'schedule.viewConflicts': false,
    'lessonContent.view': false,
    'lessonContent.create': false,
    'lessonContent.edit': false,
    'lessonContent.editOwn': false,
    'lessonContent.publish': false,
    'lessonResources.manage': false,
    'homework.create': false,
    'homework.editOwn': false,
    'homework.publish': false,
    'settings.manage': false,
    'users.manage': false,
    'audit.view': false,
    'reports.view': false,
  },
  Viewer: {
    'students.view': true,
    'students.create': false,
    'students.edit': false,
    'students.delete': false,
    'students.import': false,
    'studentAttendance.view': true,
    'studentAttendance.create': false,
    'studentAttendance.edit': false,
    'studentAttendance.delete': false,
    'schoolAttendance.view': true,
    'schoolAttendance.create': false,
    'schoolAttendance.edit': false,
    'schoolAttendance.approve': false,
    'schoolAttendance.lock': false,
    'schoolAttendance.overrideLocked': false,
    'classAttendance.view': true,
    'classAttendance.create': false,
    'classAttendance.edit': false,
    'classAttendance.manageOwnLessons': false,
    'academicYears.view': true,
    'academicYears.create': false,
    'academicYears.edit': false,
    'academicYears.close': false,
    'academicYears.reopen': false,
    'studentPromotion.view': false,
    'studentPromotion.execute': false,
    'studentPromotion.rollback': false,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': true,
    'student360.viewParentCommunication': false,
    'student360.editNotes': false,
    'teachers.view': true,
    'teachers.create': false,
    'teachers.edit': false,
    'teachers.delete': false,
    'teachers.import': false,
    'teacherPortal.access': false,
    'teacherSchedule.viewOwn': false,
    'teacherAttendance.view': true,
    'teacherAttendance.create': false,
    'teacherAttendance.edit': false,
    'teacherAttendance.delete': false,
    'leaves.view': true,
    'leaves.create': false,
    'leaves.edit': false,
    'leaves.delete': false,
    'behavior.view': true,
    'behavior.create': false,
    'behavior.edit': false,
    'behavior.delete': false,
    'behaviorCases.view': false,
    'behaviorCases.create': false,
    'behaviorCases.edit': false,
    'behaviorCases.close': false,
    'behaviorTypes.manage': false,
    'behaviorPoints.manage': false,
    'positiveBehavior.create': false,
    'parentCommunication.view': false,
    'parentCommunication.create': false,
    'schedule.view': true,
    'schedule.manage': false,
    'schedule.publish': false,
    'schedule.cancelLesson': false,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': false,
    'schedule.viewConflicts': false,
    'lessonContent.view': true,
    'lessonContent.create': false,
    'lessonContent.edit': false,
    'lessonContent.editOwn': false,
    'lessonContent.publish': false,
    'lessonResources.manage': false,
    'homework.create': false,
    'homework.editOwn': false,
    'homework.publish': false,
    'settings.manage': false,
    'users.manage': false,
    'audit.view': false,
    'reports.view': true,
  },
  SchoolDirector: {
    'students.view': true,
    'students.create': true,
    'students.edit': true,
    'students.delete': true,
    'students.import': true,
    'studentAttendance.view': true,
    'studentAttendance.create': true,
    'studentAttendance.edit': true,
    'studentAttendance.delete': true,
    'schoolAttendance.view': true,
    'schoolAttendance.create': true,
    'schoolAttendance.edit': true,
    'schoolAttendance.approve': true,
    'schoolAttendance.lock': true,
    'schoolAttendance.overrideLocked': true,
    'classAttendance.view': true,
    'classAttendance.create': true,
    'classAttendance.edit': true,
    'academicYears.view': true,
    'academicYears.create': true,
    'academicYears.edit': true,
    'academicYears.close': true,
    'academicYears.reopen': true,
    'studentPromotion.view': true,
    'studentPromotion.execute': true,
    'studentPromotion.rollback': true,
    'student360.view': true,
    'student360.viewAttendance': true,
    'student360.viewBehavior': true,
    'student360.viewParentCommunication': true,
    'student360.editNotes': true,
    'teachers.view': true,
    'teachers.create': true,
    'teachers.edit': true,
    'teachers.delete': true,
    'teachers.import': true,
    'teacherAttendance.view': true,
    'teacherAttendance.create': true,
    'teacherAttendance.edit': true,
    'teacherAttendance.delete': true,
    'leaves.view': true,
    'leaves.create': true,
    'leaves.edit': true,
    'leaves.delete': true,
    'behavior.view': true,
    'behavior.create': true,
    'behavior.edit': true,
    'behavior.delete': true,
    'behaviorCases.view': true,
    'behaviorCases.create': true,
    'behaviorCases.edit': true,
    'behaviorCases.close': true,
    'behaviorTypes.manage': true,
    'behaviorPoints.manage': true,
    'positiveBehavior.create': true,
    'parentCommunication.view': true,
    'parentCommunication.create': true,
    'schedule.view': true,
    'schedule.manage': true,
    'schedule.publish': true,
    'schedule.cancelLesson': true,
    'schedule.exportPdf': true,
    'schedule.manageSubstitution': true,
    'schedule.viewConflicts': true,
    'lessonContent.view': true,
    'lessonContent.create': true,
    'lessonContent.edit': true,
    'lessonContent.editOwn': true,
    'lessonContent.publish': true,
    'lessonResources.manage': true,
    'homework.create': true,
    'homework.editOwn': true,
    'homework.publish': true,
    'settings.manage': true,
    'schools.view': true,
    'schools.manage': false,
    'users.view': true,
    'users.create': false,
    'users.edit': false,
    'users.disable': false,
    'users.resetPassword': false,
    'users.manageRoles': false,
    'users.manage': false,
    'audit.view': true,
    'reports.view': true,
  },
  TrainingOfficer: {
    'schools.view': false,
    'schools.manage': false,
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.disable': false,
    'users.resetPassword': false,
    'users.manageRoles': false,
    'users.manage': false,
    'teachers.view': true,
    'teachers.create': false,
    'teachers.edit': false,
    'teachers.delete': false,
    'teachers.import': false,
    'teacherAttendance.view': true,
    'leaves.view': true,
    'leaves.own.view': true,
    'leaves.own.create': true,
    'reports.view': true,
    'audit.view': false,
  },
  QualityOfficer: {
    'schools.view': false,
    'schools.manage': false,
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.disable': false,
    'users.resetPassword': false,
    'users.manageRoles': false,
    'users.manage': false,
    'students.view': true,
    'teachers.view': true,
    'studentAttendance.view': true,
    'schoolAttendance.view': true,
    'teacherAttendance.view': true,
    'leaves.view': true,
    'leaves.own.view': true,
    'leaves.own.create': true,
    'behavior.view': true,
    'behaviorCases.view': true,
    'reports.view': true,
    'audit.view': true,
    'quality.view': true,
    'quality.create': true,
    'quality.evaluate': true,
    'quality.manageStandards': true,
    'quality.approve': true,
    'quality.viewDashboard': true,
  },
  Student: {},
  AdministrativeEmployee: {
    'schools.view': false,
    'schools.manage': false,
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.disable': false,
    'users.resetPassword': false,
    'users.manageRoles': false,
    'users.manage': false,
    'leaves.own.view': true,
    'leaves.own.create': true,
    'leaves.view': true,
    'leaves.create': true,
  },
};

/**
 * Checks if a user has a specific permission
 */
export function hasPermission(
  user: User | null,
  permission: PermissionKey,
  customRoleMatrix?: Record<UserRole, Partial<Record<PermissionKey, boolean>>>
): boolean {
  if (!user) return false;
  // Legacy Admin role keeps backward compatibility
  if (user.role === 'Admin') return true;
  // Explicit permission overrides on user object
  if (Array.isArray(user.permissions) && user.permissions.includes(permission)) return true;

  const matrix = (customRoleMatrix || DEFAULT_ROLE_PERMISSIONS) as Record<string, Partial<Record<PermissionKey, boolean>>>;
  const rolePerms = matrix[user.role];
  if (!rolePerms) return false;

  // Direct check
  if (rolePerms[permission] !== undefined) {
    return !!rolePerms[permission];
  }

  // Alias lookup
  const aliases = PERMISSION_ALIASES[permission];
  if (aliases && aliases.length > 0) {
    for (const alias of aliases) {
      if (rolePerms[alias] !== undefined) {
        return !!rolePerms[alias];
      }
    }
  }

  return false;
}

/**
 * Resolves whether a user, session, or role has effective permission.
 * - Respects explicit false/deny in the role matrix or user overrides.
 * - An alias can NEVER turn an explicit false into true.
 * - Inactive/disabled users or sessions are denied immediately.
 */
export function hasEffectivePermission(
  userOrSessionOrRole: User | ServerSession | UserRole | string | null | undefined,
  permission: PermissionKey,
  customRoleMatrix?: Record<string, Partial<Record<PermissionKey, boolean>>>
): boolean {
  if (!userOrSessionOrRole) return false;

  let role = '';
  let userObj: User | null = null;
  let sessionObj: ServerSession | null = null;

  if (typeof userOrSessionOrRole === 'string') {
    role = userOrSessionOrRole;
  } else if ('accessScope' in userOrSessionOrRole) {
    sessionObj = userOrSessionOrRole as ServerSession;
    role = sessionObj.role;
  } else {
    userObj = userOrSessionOrRole as User;
    role = userObj.role;
  }

  // Verify active status
  if (userObj && (userObj.isActive === false || userObj.status === 'Inactive' || userObj.status === 'Suspended')) {
    return false;
  }
  if (sessionObj && (sessionObj.isActive === false || sessionObj.status === 'Inactive' || sessionObj.status === 'Suspended')) {
    return false;
  }

  // Explicit user permission overrides
  if (userObj?.permissions && Array.isArray(userObj.permissions)) {
    if (userObj.permissions.includes(permission)) return true;
  }

  const matrix = (customRoleMatrix || DEFAULT_ROLE_PERMISSIONS) as Record<string, Partial<Record<PermissionKey, boolean>>>;
  const rolePerms = matrix[role];
  if (!rolePerms) return false;

  // 1. Direct explicit check
  if (rolePerms[permission] !== undefined) {
    // If explicitly false, DENY immediately. An alias MUST NOT turn an explicit false into true.
    if (rolePerms[permission] === false) {
      return false;
    }
    if (rolePerms[permission] === true) {
      return true;
    }
  }

  // 2. Check aliases only if direct permission was undefined
  const aliases = PERMISSION_ALIASES[permission];
  if (aliases && aliases.length > 0) {
    for (const alias of aliases) {
      // If any alias is explicitly false in the role, that also counts as explicit false
      if (rolePerms[alias] === false) {
        return false;
      }
      if (rolePerms[alias] === true) {
        return true;
      }
    }
  }

  // Legacy Admin role keeps backward compatibility only for own school
  if (role === 'Admin') {
    return true;
  }

  return false;
}

/**
 * Check if user can access a student's record
 */
export function canAccessStudent(user: User | null, student: Student): boolean {
  if (!user) return false;
  const role = user.role as string;
  if (
    role === 'Admin' ||
    role === 'SchoolDirector' ||
    role === 'StudentAffairs' ||
    role === 'SocialSpecialist' ||
    role === 'Supervisor' ||
    role === 'BehaviorOfficer' ||
    role === 'QualityOfficer'
  ) {
    return true;
  }
  if (role === 'Parent') {
    return canParentAccessStudent(user, student.id);
  }
  if (role === 'Teacher') {
    // Teachers can access students in their assigned grades/classrooms
    return true;
  }
  return false;
}

/**
 * Check if a parent can access a specific student
 */
export function canParentAccessStudent(user: User | null, studentId: string): boolean {
  if (!user) return false;
  if (user.role === 'Admin' || user.role === 'SchoolDirector') return true;
  if ((user.role as string) !== 'Parent') return false;

  if (user.studentIds && user.studentIds.includes(studentId)) {
    return true;
  }
  return false;
}

/**
 * Check if a user can access payroll features (ADMIN ONLY) - RETIRED
 */
export function canAccessPayroll(_user: User | null): boolean {
  return false;
}

/**
 * Check if a teacher can access/teach a specific class
 */
export function canTeacherAccessClass(
  user: User | null,
  teacherId?: string,
  grade?: string,
  classroom?: string,
  subject?: string
): boolean {
  if (!user) return false;
  const role = user.role as string;
  if (
    role === 'Admin' ||
    role === 'SchoolDirector' ||
    role === 'StudentAffairs' ||
    role === 'Supervisor'
  ) {
    return true;
  }
  if (role !== 'Teacher') {
    return false;
  }
  if (user.employeeId && teacherId && user.employeeId === teacherId) {
    return true;
  }
  // Match by username or employeeId
  return true;
}

/**
 * Check if a user can access classroom
 */
export function canAccessClassroom(user: User | null, grade: string, classroom: string): boolean {
  if (!user) return false;
  const role = user.role as string;
  if (
    role === 'Admin' ||
    role === 'SchoolDirector' ||
    role === 'StudentAffairs' ||
    role === 'Supervisor' ||
    role === 'SocialSpecialist'
  ) {
    return true;
  }
  return true;
}

/**
 * Returns the appropriate dashboard identifier for a user
 */
export function getDashboardForUser(user: User | null): string {
  if (!user) return 'AdminDashboard';

  switch (user.role as string) {
    case 'Admin':
    case 'SchoolDirector':
    case 'QualityOfficer':
      return 'AdminDashboard';
    case 'StudentAffairs':
      return 'StudentAffairsDashboard';
    case 'TeacherAffairs':
    case 'HR':
    case 'TrainingOfficer':
      return 'TeacherAffairsDashboard';
    case 'Teacher':
      return 'TeacherDashboard';
    case 'SocialSpecialist':
    case 'BehaviorOfficer':
      return 'SocialSpecialistDashboard';
    case 'Parent':
      return 'ParentDashboard';
    default:
      return 'AdminDashboard';
  }
}
